---
- name: restart mariadb
  systemd:
    name: mariadb
    state: restarted

- name: Restart Apache2
  systemd:
    name: httpd
    state: restarted

- name: Start Zabbix Agent
  systemd:
    name: zabbix-agent
    state: restarted
    enabled: yes
