---
- include: common.yml
- include: mariadb.yml
#- include: apache.yml
#- include: php.yml

#- include: cacti.yml
#- include: zabbix.yml
#- include: prometheus.yml

- name: Create Zabbix DB user
  shell: |
    mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "CREATE USER '"{{ mysql_zabbix_user }}"'@'localhost' IDENTIFIED BY '"{{ mysql_zabbix_user_pwd }}"'"
    mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "GRANT ALL PRIVILEGES ON "{{ mysql_zabbix_db }}".* TO '"{{ mysql_zabbix_user }}"'@'localhost' WITH GRANT OPTION"
    mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "FLUSH PRIVILEGES;"
  tags: zabbix
