- name: Install PHP packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - php-pear
      - php-common
      - php-gd
      - php-devel
      - php
      - php-mbstring
      - php-cli
      - php-mysql
      - php-snmp
  tags: php

- name: Configure time zone in php.ini
  shell: sed -i "s/^[; ]*date\.timezone[ ]*=.*$/date.timezone = Europe\/Moscow/gm" /etc/php.ini
  tags: php
