---
- name: Download and install Zabbix repo rpm-file
  yum:
    name: https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-2.el7.noarch.rpm
    state: present
  tags: zabbix

# активировать репозиторий опциональных rpm пакетов в системе, где вы
# запускаете веб-интерфейс Zabbix:
- name: Activate repo additional packages
  shell: yum-config-manager --enable rhel-7-server-optional-rpms
  tags: zabbix


- name: Install Zabbix server and Zabbix web-client
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - zabbix-server-mysql
      - zabbix-web-mysql
  tags: zabbix


- name: Create Zabbix DB
  shell: mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "CREATE DATABASE \`"{{ mysql_zabbix_db }}"\` DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci"
  tags: zabbix


- name: Create Zabbix DB user
  shell: |
    mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "CREATE USER '"{{ mysql_zabbix_user }}"'@'localhost' IDENTIFIED BY '"{{ mysql_zabbix_user_pwd }}"'"
    mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "GRANT ALL PRIVILEGES ON "{{ mysql_zabbix_db }}".* TO '"{{ mysql_zabbix_user }}"'@'localhost' WITH GRANT OPTION"
    mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "FLUSH PRIVILEGES;"
  tags: zabbix

- name: Unzip Zabbix DB schema
  shell: sudo gunzip /usr/share/doc/zabbix-server-mysql*/create.sql.gz
  tags: zabbix

- name: Init Zabbix DB
  shell: mysql -u 'root' -p"{{ mysql_root_pwd }}"  -D "{{ mysql_zabbix_db }}" -h 'localhost' --port='3306' < /usr/share/doc/zabbix-server-mysql-4.2.8/create.sql
  tags: zabbix

- name: Start Zabbix Server
  systemd:
    name: zabbix-server
    state: started
    enabled: yes
  tags: zabbix

- name: Install Zabbix Agent
  yum:
    name: zabbix-agent
    state: present
  notify: Start Zabbix Agent
