filebeat:
  prospectors:
    -
      paths:
        - /var/log/secure
        - /var/log/messages
        - /var/log/*.log

      input_type: log

      document_type: syslog

  registry_file: /var/lib/filebeat/registry

output:
  logstash:
    hosts: ["192.168.50.20:5044"]
    bulk_max_size: 1024

#    tls:
#      certificate_authorities: ["/etc/pki/tls/certs/logstash-forwarder.crt"]

shipper:

logging:
  files:
    rotateeverybytes: 10485760 # = 10MB
