---
- name: Install and configure FreeIPA-server
  hosts:
    - ipa.linux.otus
  gather_facts: yes
  remote_user: vagrant
  become: yes

  vars:
    ipa_hostname: "ipa.linux.otus"
    ipa_domain: "ipa.linux.otus"
    ipa_realm: "IPA.LINUX.OTUS"
    ds_pass: "12345678"
    admin_pass: "12345678"

  tasks:
  - name: Install FreeIPA-server
    yum:
      name: "ipa-server"
      state: present

  - name: Configure FreeIPA-client
    shell: |
      ipa-server-install
      --hostname=ipa.linux.otus
      --domain=ipa.linux.otus
      --realm=IPA.LINUX.OTUS
      --ds-password=12345678
      --admin-password=12345678
      --mkhomedir
      --unattended
