---
# Role web-srv

#- name: Upgrade all packages
#  yum:
#    name: '*'
#    state: latest

- name: Install EPEL repository
  yum:
    name: epel-release
    state: latest
    update_cache: yes
  tags: common

- name: Installation of auxiliary packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - ansible-lint
      - nano
      - mc
      - tmux
      - tree
      - wget
  tags: common

- name: Copy OpenSSL-cert
  copy:
    src: logstash-forvarder.crt
    dest: /etc/pki/tls/certs/
    owner: root
    group: root
    mode: 0755
  tags: common
