---
# Role web-srv

- name: Install MariaDB package
  yum:
    name: mariadb-server
    state: latest
  tags: mariadb

- name: Start MariaDB service
  systemd:
    name: mariadb
    state: started
    enabled: yes
  tags: mariadb

- name: Set MariaDB root password
  shell: mysqladmin -u root password "{{ mysql_root_pwd }}"
  tags: mariadb

- name: Allow remote connect to the MariaDB server
  blockinfile:
    path: /etc/my.cnf.d/server.cnf
    block: |
      [mysqld]
      bind-address    = 0.0.0.0
  tags: mariadb

- name: Restart MariaDB
  systemd:
    name: mariadb
    state: restarted
  tags: mariadb

- name: Create root and allow remote connection to MariaDB
  shell: |
    mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "CREATE USER 'root'@'localhost' IDENTIFIED BY '"{{ mysql_root_pwd }}"'"
    mysql -u 'root' -p"{{ mysql_root_pwd }}"  -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION"
  tags: mariadb
