---
# Role web-srv

- name: Install nginx
  yum:
    name: nginx
    state: latest
  tags: nginx

#- name: Copy nginx.conf
#  copy:
#    src: nginx.conf
#    dest: /etc/nginx/
#    owner: root
#    group: root
#    mode: 0755
#  tags: nginx

- name: nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
  tags: nginx
