---
# tasks file for roles/freeipa

- name: Install FreeIPA-server
  yum:
    name: "ipa-server"
    state: present

- name: Configure FreeIPA-server
  shell: >
    ipa-server-install
    --hostname={{ ipa_hostname }}
    --domain={{ ipa_domain }}
    --realm={{ ipa_realm }}
    --ds-password={{ ds_pass }}
    --admin-password={{ admin_pass }}
    --mkhomedir
    --unattended

- name: Init token for admin-user
  shell: echo {{ admin_pass }} | kinit admin


- name: Add new user
  shell: echo {{ user_pass }} | ipa user-add {{ user_login }} --first={{ first_name }} --last={{ last_name }} --password
