---
# Role elk

- name: Copy kibana.repo
  copy:
    src: kibana.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0755
  tags: kibana

- name: Install Kibana
  yum:
    name: kibana
    state: latest
  tags: kibana

- name: Copy kibana.yml
  copy:
    src: kibana.yml
    dest: /opt/kibana/config/
    owner: root
    group: root
    mode: 0755
  tags: kibana

- name: Starting kibana
  systemd:
    name: kibana
    state: started
    enabled: yes
  tags: kibana

- name: Add Kibana admin user
  shell: echo '"{{ kibana_admin_pwd }}"' | htpasswd -i -c /etc/nginx/htpasswd.users {{ kibana_admin }}
  tags: kibana

- name: Copy kibana.conf
  copy:
    src: kibana.conf
    dest: /etc/nginx/conf.d/
    owner: root
    group: root
    mode: 0755
  tags: kibana

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
  tags: kibana

- name: Download and install dashboard
  shell: |
    cd ~ &&  curl -L -O https://download.elastic.co/beats/dashboards/beats-dashboards-1.1.0.zip
    unzip beats-dashboards-*.zip
    cd beats-dashboards-* && ./load.sh

- name: Customize Filebeat on Elasticsearch
  shell: |
    cd ~ &&  curl -O https://gist.githubusercontent.com/thisismitch/3429023e8438cc25b86c/raw/d8c479e2a1adcea8b1fe86570e42abab0f10f364/filebeat-index-template.json
    curl -XPUT 'http://localhost:9200/_template/filebeat?pretty' -d@filebeat-index-template.json
