---
# Role elk

- name: Copy logstash.repo
  copy:
    src: logstash.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0755
  tags: logstash

- name: Install logstash
  yum:
    name: logstash
    state: latest
  tags: logstash

#- name: Create dir for OpenSSL cert
#  file:
#    path: /etc/pki/tls/certs
#    state: directory
#    mode: 0755
#  tags: logstash

#- name: Create dir for OpenSSL key
#  file:
#    path: /etc/pki/tls/private
#    state: directory
#    mode: 0755
#  tags: logstash

#- name: Copy openssl.cnf
#  template:
#    src: openssl.cnf.j2
#    dest: /etc/pki/tls/openssl.cnf
#    owner: root
#    group: root
#    mode: 0755
#  tags: logstash

#- name: Copy OpenSSL-key
#  copy:
#    src: logstash-forvarder.key
#    dest: /etc/pki/tls/private/logstash-forvarder.key
#    owner: root
#    group: root
#    mode: 0755
#  tags: logstash

#- name: Copy OpenSSL-cert
#  copy:
#    src: logstash-forvarder.crt
#    dest: /etc/pki/tls/certs/logstash-forvarder.crt
#    owner: root
#    group: root
#    mode: 0755
#  tags: logstash


- name: Copy 02-beats-input.conf
  copy:
    src: 02-beats-input.conf
    dest: /etc/logstash/conf.d/
    owner: root
    group: root
    mode: 0755
  tags: logstash

- name: Copy 10-syslog-filter.conf
  copy:
    src: 10-syslog-filter.conf
    dest: /etc/logstash/conf.d/
    owner: root
    group: root
    mode: 0755
  tags: logstash

- name: Copy 30-elasticsearch-output.conf
  copy:
    src: 30-elasticsearch-output.conf
    dest: /etc/logstash/conf.d/
    owner: root
    group: root
    mode: 0755
  tags: logstash

- name: Restart Logstash
  systemd:
    name: logstash
    state: restarted
    enabled: yes
  tags: logstash
