---
- name: Create dir /bacula/backup
  file:
    path: /bacula/backup
    state: directory
    owner: bacula
    group: bacula
    mode: 0700
    recurse: yes
  tags: bacula

- name: Create dir /bacula/restore
  file:
    path: /bacula/restore
    state: directory
    owner: bacula
    group: bacula
    mode: 0700
    recurse: yes
  tags: bacula

- name: Copy bacula-fd.conf to /etc/bacula/
  template:
    src: client_bacula-fd.conf.j2
    dest: /etc/bacula/bacula-fd.conf
    owner: root
    group: bacula
    mode: 0700
  tags: bacula

- name: Copy bconsole.conf to /etc/bacula/
  template:
    src: bconsole.conf.j2
    dest: /etc/bacula/bconsole.conf
    owner: root
    group: bacula
    mode: 0700
  tags: bacula

- name: Start Bacula FD (File Daemon) service
  systemd:
    name: bacula-fd
    state: started
    enabled: yes
  tags: bacula
