---
- name: Change DB provider for Bacula
  shell: echo "1" | alternatives --config libbaccats.so
  tags: bacula

- name: Create dir /bacula/backup
  file:
    path: /bacula/backup
    state: directory
    owner: bacula
    group: bacula
    mode: 0700
    recurse: yes
  tags: bacula

- name: Create dir /bacula/restore
  file:
    path: /bacula/restore
    state: directory
    owner: bacula
    group: bacula
    mode: 0700
    recurse: yes
  tags: bacula

- name: Create dir /etc/bacula/conf.d
  file:
    path: /etc/bacula/conf.d
    state: directory
    owner: root
    group: bacula
    mode: 0755
  tags: bacula

- name: Copy bacula-dir.conf to /etc/bacula/
  template:
    src: server_bacula-dir.conf.j2
    dest: /etc/bacula/bacula-dir.conf
    owner: root
    group: bacula
    mode: 0700
  tags: bacula

- name: Copy bacula-sd.conf to /etc/bacula/
  template:
    src: server_bacula-sd.conf.j2
    dest: /etc/bacula/bacula-sd.conf
    owner: root
    group: bacula
    mode: 0700
  tags: bacula

- name: Copy bconsole.conf to /etc/bacula/
  template:
    src: bconsole.conf.j2
    dest: /etc/bacula/bconsole.conf
    owner: root
    group: bacula
    mode: 0700
  tags: bacula


#- name: Copy clients.conf to /etc/bacula/conf.d
#  template:
#    src: clients.conf.j2
#    dest: /etc/bacula/conf.d/clients.conf
#    owner: root
#    group: bacula
#    mode: 0700
#  tags: bacula

#- name: Copy filesets.conf to /etc/bacula/conf.d
#  template:
#    src: filesets.conf.j2
#    dest: /etc/bacula/conf.d/filesets.conf
#    owner: root
#    group: bacula
#    mode: 0700
#  tags: bacula

#- name: Copy pools.conf to /etc/bacula/conf.d
#  template:
#    src: pools.conf.j2
#    dest: /etc/bacula/conf.d/pools.conf
#    owner: root
#    group: bacula
#    mode: 0700
#  tags: bacula


- name: Start Bacula DIR (Director) service
  systemd:
    name: bacula-dir
    state: started
    enabled: yes
  tags: bacula

- name: Start Bacula SD (Storage Daemon) service
  systemd:
    name: bacula-sd
    state: started
    enabled: yes
  tags: bacula

- name: Start Bacula FD (File Daemon) service
  systemd:
    name: bacula-fd
    state: started
    enabled: yes
  tags: bacula
