---
- name: Install EPEL repository
  yum:
    name: epel-release
    state: latest
  tags: common

- name: Install Bacula client and other packages
  yum:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
      - bacula-client
      - bacula-console
      - nano
  tags: common
