---
# Первичная настройка
- include: common.yml
# Установка prometheus-node-exporter
#- include: prom.yml
# Установка веб-сервера nginx
- include: web.yml
#- include: wp.yml
#- include: mysql.yml
#- include: mysql-exporter.yml
#- include: nginx-exporter.yml
