---
- name: Install nginx
  yum:
    name: nginx
    state: latest
  tags: web

- name: Install php
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - php
      - php-bcmath
      - php-bz2
      - php-cli
      - php-common
      - php-intl
      - php-gd
      - php-mbstring
      - php-mysql
      - php-pear
      - php-zip
      - php-fpm
      - php-dom
      - php-fileinfo
      - php-iconv
      - php-json
      - php-pdo
      - php-phar
      - php-simplexml
      - php-xml
      - php-curl
  tags: web

- name: Configure time zone in php.ini
  shell: sed -i "s/^[; ]*date\.timezone[ ]*=.*$/date.timezone = Europe\/Moscow/gm" /etc/php.ini
  tags: web

- name: Copy nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/
    owner: root
    group: root
    mode: 0755
  tags: web

- name: nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
  tags: web

- name: Enable php-fpm
  systemd:
    name: php-fpm
    state: started
    enabled: yes
  tags: web
