---

- name: Copy rsyslog conf to client
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0644
  tags: rsyslog

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes
  tags: rsyslog
