---
- name: Create temp directory
  file:
    path: /root/tmp
    state: directory
    mode: 0755
  tags: wordpress

- name: Download wordpress
  shell: wget -P /root/tmp http://wordpress.org/latest.tar.gz
  tags: wordpress

- name: Untar wp
  shell: cd /root/tmp && tar -xvzf latest.tar.gz -C /var/www/html
  tags: wordpress


- name: Copy wp conf
  copy:
    src: wp.conf
    dest: /etc/nginx/conf.d
    owner: root
    group: root
    mode: 0644
  tags: wordpress

- name: nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
  tags: web
