---
- name: Install EPEL repository
  yum:
    name: epel-release
    state: present
  tags: common

- name: Install php and php components
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - php
      - php-bcmath
      - php-bz2
      - php-intl
      - php-gd
      - php-mbstring
      - php-mysql
      - php-mysql
      - php-zip
      - php-fpm
      - php-dom
      - php-fileinfo
      - php-iconv
      - php-json
      - php-pdo
      - php-phar
      - php-simplexml
      - php-xml
      - php-curl
  tags: web

- name: Enable php-fpm
  systemd:
    name: php-fpm
    enabled: yes
  tags: web

- name: Install nginx
  yum:
    name: nginx
    state: latest
  notify: Restart nginx
  tags: web

- name: nginx
  systemd:
    name: nginx
    enabled: yes
  tags: web
