---
- name: Install Cacti
  yum:
    name: cacti
    state: latest
  tags: cacti

- name: Install SNMP and RRDTool packages
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - php-snmp
      - net-snmp-utils
      - net-snmp-libs
      - rrdtool
  tags: cacti

- name: Init Cacti DB
  shell: mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -D "{{ mysql_cacti_db }}" < $(rpm -ql cacti | grep cacti.sql)
  tags: mariadb

- name: Create Cacti DB
  shell: mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "CREATE DATABASE \`"{{ mysql_cacti_db }}"\` DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci"
  tags: mariadb

- name: Create Cacti DB user
  shell: |
    mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "CREATE USER '"{{ mysql_cacti_user }}"'@'localhost' IDENTIFIED BY '"{{ mysql_cacti_user_pwd }}"'"
    mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "GRANT ALL PRIVILEGES ON "{{ mysql_cacti_db }}".* TO '"{{ mysql_cacti_user }}"'@'localhost' WITH GRANT OPTION"
  tags: mariadb
