---
# tasks file for roles/nginx
#

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: debian.yml
  when: ansible_os_family == 'Debian'

- name:
  debug:
    msg: "Hello from {{ ansible_os_family }}"
