---
- name: Change DB provider for Bacula
  shell: echo "1" | sudo alternatives --config libbaccats.so
  tags: bacula

- name: Create dir /bacula/backup
  file:
    path: /bacula/backup
    state: directory
    owner: bacula
    group: bacula
    mode: 0700
    recurse: yes
  tags: bacula

- name: Create dir /bacula/restore
  file:
    path: /bacula/restore
    state: directory
    owner: bacula
    group: bacula
    mode: 0700
    recurse: yes
  tags: bacula

- name: Change privileges for /bacula/ dir
  file:
    path: /bacula
    state: directory
    mode: 0700
  tags: bacula

- name: Create dir /etc/bacula/conf.d
  file:
    path: /etc/bacula/conf.d
    state: directory
    owner: root
    group: bacula
    mode: 0755
  tags: bacula

- name: Copy clients.conf to /etc/bacula/conf.d
  template:
    src: clients.conf.j2
    dest: /etc/bacula/conf.d/clients.conf
    owner: root
    group: bacula
    mode: 0700
  tags: bacula

- name: Copy filesets.conf to /etc/bacula/conf.d
  template:
    src: filesets.conf.j2
    dest: /etc/bacula/conf.d/filesets.conf
    owner: root
    group: bacula
    mode: 0700
  tags: bacula

- name: Copy pools.conf to /etc/bacula/conf.d
  template:
    src: pools.conf.j2
    dest: /etc/bacula/conf.d/pools.conf
    owner: root
    group: bacula
    mode: 0700
  tags: bacula

- name: Copy bacula-dir.conf to /etc/bacula/
  template:
    src: bacula-dir.conf.j2
    dest: /etc/bacula/bacula-dir.conf
    owner: root
    group: bacula
    mode: 0700
  tags: bacula

- name: Copy bacula-sd.conf to /etc/bacula/
  template:
    src: bacula-sd.conf.j2
    dest: /etc/bacula/bacula-sd.conf
    owner: root
    group: bacula
    mode: 0700
  tags: bacula

#- name: Change password for Bacula DIR
#  shell: |
#    DIR_PASSWORD=`date +%s | sha256sum | base64 | head -c 33`
#    sed -i "s/@@DIR_PASSWORD@@/${DIR_PASSWORD}/" /etc/bacula/bacula-dir.conf
#    sed -i "s/@@DIR_PASSWORD@@/${DIR_PASSWORD}/" /etc/bacula/bconsole.conf

#- name: Change password for Bacula DIR
#  shell: |
#    SD_PASSWORD=`date +%s | sha256sum | base64 | head -c 33`
#    sed -i "s/@@SD_PASSWORD@@/${SD_PASSWORD}/" /etc/bacula/bacula-sd.conf
#    sed -i "s/@@SD_PASSWORD@@/${SD_PASSWORD}/" /etc/bacula/bacula-dir.conf

#- name: Change password for Bacula DIR
#  shell: |
#    FD_PASSWORD=`date +%s | sha256sum | base64 | head -c 33`
#    sed -i "s/@@FD_PASSWORD@@/${FD_PASSWORD}/" /etc/bacula/bacula-dir.conf
#    sed -i "s/@@FD_PASSWORD@@/${FD_PASSWORD}/" /etc/bacula/bacula-fd.conf

- name: Start Bacula DIR (Director) service
  systemd:
    name: bacula-dir
    state: started
    enabled: yes
  tags: bacula

- name: Start Bacula SD (Storage Daemon) service
  systemd:
    name: bacula-sd
    state: started
    enabled: yes
  tags: bacula

- name: Start Bacula FD (File Daemon) service
  systemd:
    name: bacula-fd
    state: started
    enabled: yes
  tags: bacula
