---
- name: Install Bacula server and other packages
  yum:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
      - ansible-lint
      - bacula-director
      - bacula-storage
      - bacula-console
      - bacula-client
      - nano
      - mc
      - tmux
  tags: common
