---
- hosts: srv
  become: yes

  tasks:

  - name: Install package nginx
    apt:
      name=nginx
      update_cache=yes
    sudo: yes

  - name: Starting service nginx
    service:
      name=nginx
      state=started
    sudo: yes
