---
- name: Install NGINX package using apt
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Replace standard HTML file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
