---
- name: Install NGINX package
  apt:
    name: nginx
    state: present
  notify: restart nginx

- name: Replace standard HTML file
  template:
    src: index.html.j2
    dest: /var/www/html/index.nginx-debian.html
  notify: restart nginx
