---
- name: Install Bacula client and other packages
  yum:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
      - bacula-client
      - nano
  tags: common

- name: Copy bacula-fd.conf to /etc/bacula/
  template:
    src: bacula-fd.conf.j2
    dest: /etc/bacula/bacula-fd.conf
    owner: root
    group: bacula
    mode: 0700
  tags: bacula

- name: Start Bacula FD (File Daemon) service
  systemd:
    name: bacula-fd
    state: started
    enabled: yes
  tags: bacula
