---
# Role web-srv

- name: Create Wordpress DB
  shell: mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "CREATE DATABASE \`"{{ wp_db }}"\` DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci"
  tags: wordpress

- name: Create Wordpress DB user
  shell: |
    mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "CREATE USER '"{{ wp_user }}"'@'localhost' IDENTIFIED BY '"{{ wp_pwd }}"'"
    mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "GRANT ALL PRIVILEGES ON "{{ wp_db }}".* TO '"{{ wp_user }}"'@'localhost' WITH GRANT OPTION"
    mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "FLUSH PRIVILEGES"
  tags: wordpress

- name: Create temp directory
  file:
    path: /root/tmp
    state: directory
    mode: 0755
  tags: wordpress

- name: Download wordpress
  shell: wget -P /root/tmp http://wordpress.org/latest.tar.gz
  tags: wordpress

- name: Untar wp
  shell: cd /root/tmp && tar -xvzf latest.tar.gz -C {{ document_root }}
  tags: wordpress

- name: Change html dir permissions
  file:
    path: "{{ document_root }}"
    owner: nginx
    group: nginx
    mode: 0777
    recurse: yes
  tags: wordpress

- name: Copy wp.conf
  template:
    src: wp.conf.j2
    dest: /etc/nginx/conf.d/wp.conf
    owner: root
    group: root
    mode: 0644
  tags: wordpress

- name: nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
  tags: wordpress
