---
- name: Install nginx on staging servers
  hosts: centos
  gather_facts: yes
  become: yes

  tasks:

    - name: Install EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Install NGINX package
      yum:
        name: nginx
        state: present
      notify: restart nginx

  handlers:

  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
      enabled: yes 
