---
- name: Install DBMS MariaDB package
  yum:
    name: mariadb-server
    state: latest
  tags: mariadb

- name: Start MariaDB service
  systemd:
    name: mariadb
    state: started
    enabled: yes
  tags: mariadb

- name: Set MariaDB root password
  shell: mysqladmin -u root password "{{ mysql_root_pwd }}"
  tags: mariadb

- name: Allow remote connect to the MariaDB server
  blockinfile:
    path: /etc/my.cnf.d/server.cnf
    block: |
      [mysqld]
      bind-address    = 0.0.0.0
  tags: mariadb

- name: Restart MariaDB service (notify not worked)
  systemd:
    name: mariadb
    state: restarted
  tags: mariadb

- name: Create root and allow remote connection to MariaDB
  shell: |
    mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "CREATE USER 'root'@'localhost' IDENTIFIED BY '"{{ mysql_root_pwd }}"'"
    mysql -u 'root' -p"{{ mysql_root_pwd }}"  -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION"
  tags: mariadb

- name: Create Cacti DB
  shell: mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "CREATE DATABASE \`"{{ mysql_cacti_db }}"\` DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci"
  tags: mariadb

- name: Create Cacti DB user
  shell: |
    mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "CREATE USER '"{{ mysql_cacti_user }}"'@'localhost' IDENTIFIED BY '"{{ mysql_cacti_user_pwd }}"'"
    mysql -u 'root' -p"{{ mysql_root_pwd }}" -h 'localhost' --port='3306' -e "GRANT ALL PRIVILEGES ON "{{ mysql_cacti_db }}".* TO '"{{ mysql_cacti_user }}"'@'localhost' WITH GRANT OPTION"
  tags: mariadb
